---
abstract: 'Easily obtain current TAI time, using UNIX epoch.'
author:
  - 'TTKCIAR <ttk@ciar.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: time-tai-simple
requires:
  Data::Dumper: '2.0'
  File::Slurp: '9999.19'
  POSIX::RT::Clock: '0.015'
  Test::Most: '0.30'
  Time::HiRes: '1.9'
version: '1.02'
